### ISSUE TITLE
Cannot start portal

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/portal9#65]
#### Installation information

- jumpscale version: master branch
- operating system: Docker on a Linux Ubuntu trusty

#### Detailed description
After installing the the latest jumpscal core9 and portal9 from master branch, checking the portal shows that it did not start.

#### Steps to reproduce
- Install jumpscale9 and portal9 from master branch
- Start portal (if not started during install)

#### Relevant stacktraces
**START**
[Thu24 20:39] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
Reading package lists... Done
Building dependency tree       
Reading state information... Done
redis-server is already the newest version (2:3.0.6-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sh: 1: cannot create /sys/kernel/mm/transparent_hugepage/enabled: Read-only file system
sysctl: setting key "vm.overcommit_memory": Read-only file system
redis-server  --port 0 --unixsocket /tmp/redis.sock --maxmemory 100000000
[Thu24 20:39] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 19, in cli
    start()
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 34, in start
    server = j.portal.tools.server.get()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalServerFactory.py", line 19, in get
    return PortalServer.PortalServer()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalServer.py", line 134, in __init__
    self.auth = PortalAuthenticatorMongoEngine()
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py", line 15, in __init__
    self.createUser('admin', 'admin', 'demo@1234.com', ['admin'], 'domain.com')
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py", line 39, in createUser
    if self.userExists(username):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalAuthenticatorMongoEngine.py", line 36, in userExists
    return j.portal.tools.models.system.User.get(self._getkey(self.usermodel, user))
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/data/models/Models.py", line 85, in get
    res = cls.objects.get(id=guid)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 238, in get
    result = next(queryset)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1407, in __next__
    raw_doc = next(self._cursor)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1481, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/base.py", line 1515, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 90, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/queryset/transform.py", line 95, in query
    value = field.prepare_query_value(op, value)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 457, in prepare_query_value
    return self.to_mongo(value)
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 453, in to_mongo
    self.error(str(e))
  File "/usr/local/lib/python3.5/dist-packages/mongoengine/base/fields.py", line 155, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: 'admin' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
'admin' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
Exception ignored in: <function _removeHandlerRef at 0x7fa89882b510>
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 735, in _removeHandlerRef
  File "/usr/lib/python3.5/logging/__init__.py", line 218, in _acquireLock
  File "/usr/lib/python3.5/threading.py", line 141, in acquire
TypeError: 'NoneType' object is not callable
**ERROR**

**Comment by alichaddad** [comment]
This isn't the case anymore, portal installation works fine on master.

**Comment by ahussein** [comment]
The issue occur again after installing from master, but with different error
`
[Mon04 15:31] - SystemProcess.py    :661 :j.sal.process                  - DEBUG    - Checking whether at least 1 processes redis-server are running
Traceback (most recent call last):
  File "portal_start.py", line 40, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 19, in cli
    start()
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "portal_start.py", line 34, in start
    server = j.portal.tools.server.get()
AttributeError: 'Portal' object has no attribute 'tools'
'Portal' object has no attribute 'tools'
**ERROR**

`
This is due to the change done to install portal only using prefab, now the plugin generate is not called and the portal path is not added to the js9 plugins
`
In [3]: j.core.state.configGet('plugins', defval={})
Out[3]: 
{'JumpScale9': '/opt/code/github/jumpscale/core9/JumpScale9/',
 'JumpScale9AYS': '/opt/code/github/jumpscale/ays9/JumpScale9AYS',
 'JumpScale9Lib': '/opt/code/github/jumpscale/lib9/JumpScale9Lib',
 'JumpScale9Prefab': '/opt/code/github/jumpscale/prefab9/JumpScale9Prefab'}
`

**Comment by john-kheir** [comment]
Verified
