### ISSUE TITLE
Error when editing portal group

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/portal9#66]
#### Installation information

- jumpscale version:9.1.1
- operating system:Ubuntu

#### Detailed description
It is not possible to edit a group that does not have users, nor it is possible to remove users from a group.

#### Steps to reproduce
Create a new group in the portal and edit the group.

#### Relevant stacktraces
```
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/auth.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/opt/jumpscale9/apps/portals/portalbase/system/system__usermanager/methodclass/system_usermanager.py", line 175, in editGroup
    users_remove = [x for x in users_old if x not in users]
  File "/opt/jumpscale9/apps/portals/portalbase/system/system__usermanager/methodclass/system_usermanager.py", line 175, in <listcomp>
    users_remove = [x for x in users_old if x not in users]
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by john-kheir** [comment]
Verified
