### ISSUE TITLE
Installing portal9 on MacOS fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/portal9#93]
#### Installation information

- jumpscale version: master (9.3.0)
- operating system: MacOS

#### Detailed description

When executing `pip3 install -e .` in the updated repo `/Users/yves/code/github/jumpscale/ays9` I get the following error:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/yves/code/github/jumpscale/portal9/setup.py", line 95, in <module>
        'developement': develop
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/yves/code/github/jumpscale/portal9/setup.py", line 37, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
        func(*args)
      File "/Users/yves/code/github/jumpscale/portal9/setup.py", line 19, in _post_install
        j.tools.jsloader.copyPyLibs()
      File "/Users/yves/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 427, in copyPyLibs
        createdir=True)
      File "/Users/yves/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 281, in copyDirTree
        srcname, dstname, createDirIfNeeded=False, overwriteFile=overwriteFiles)
      File "/Users/yves/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 82, in wrapper
        raise ValueError("Argument %s in %s%s expects a file path! %s is not a file." % (parameter.name, jslocation(), func.__name__, value))
    ValueError: Argument fileFrom in j.sal.fs.copyFile expects a file path! /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages is not a file.
    Argument fileFrom in j.sal.fs.copyFile expects a file path! /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages is not a file.

    ----------------------------------------
  Rolling back uninstall of JumpScale9Portal
Command "/usr/local/opt/python3/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/yves/code/github/jumpscale/portal9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/yves/code/github/jumpscale/portal9/
```

What does this mean?

**Comment by hossamabdullah** [comment]
I can not reproduce it
